CREATE DATABASE QLNhaTre
GO
USE QLNhaTre
GO





CREATE TABLE KHOILOP (
	MAKHOI INT IDENTITY(1,1) PRIMARY KEY,
	TENKHOI NVARCHAR(50),
	SSTOIDA INT
)
GO

CREATE TABLE NAMHOC (
	MANAMHOC INT IDENTITY(1,1) PRIMARY KEY,
	NAMBD INT,
	NAMKT INT,
	NAMBDKT AS CAST(NAMBD AS VARCHAR)+'-'+ CAST(NAMKT AS VARCHAR)
)
GO



CREATE TABLE LOP (
	MALOP INT IDENTITY(1,1) PRIMARY KEY,
	TENLOP NVARCHAR(50),
	MAKHOI INT FOREIGN KEY REFERENCES KHOILOP(MAKHOI),
	MANAMHOC INT FOREIGN KEY REFERENCES NAMHOC(MANAMHOC)
)
GO
	 
CREATE TABLE GIAOVIEN (
	MAGV INT IDENTITY(1,1) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	GIOITINH NVARCHAR(10),
	NGAYSINH DATE,
	DANTOC NVARCHAR(20),
	TONGIAO NVARCHAR(50),
	DIACHI NVARCHAR(50),
	SDT VARCHAR(15),	
	TRINHDO NVARCHAR(50),
	NGAYVAOLAM DATE,
	MALOP INT FOREIGN KEY REFERENCES LOP(MALOP)
)
GO

CREATE TABLE HOCSINH (
	MAHS INT IDENTITY(1,1) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	GIOITINH NVARCHAR(10),
	NGAYSINH DATE,
	MALOP INT FOREIGN KEY REFERENCES LOP(MALOP),
	NGAYVAOHOC DATE,
	DIACHI NVARCHAR(50),
	HOTENCHA NVARCHAR(50),
	SDTCHA VARCHAR(15),
	HOTENME NVARCHAR(50),
	SDTME VARCHAR(15),
)
GO

CREATE TABLE SUCKHOE (
	MASK INT IDENTITY(1,1) PRIMARY KEY,
	MAHS INT FOREIGN KEY REFERENCES HOCSINH(MAHS),
	
	THANGDO INT,
	CHIEUCAO FLOAT,
	DGCC NVARCHAR(50),
	CANNANG FLOAT,
	DGCN NVARCHAR(50),
	DGC NVARCHAR(50)
)
GO

CREATE TABLE NGUOIDUNG (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TAIKHOAN VARCHAR(50),
	MATKHAU VARCHAR(50) default '3244185981728979115075721453575112',-- 123
	MAGV INT FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
	QUYEN NVARCHAR(50)
)
GO




--
CREATE TRIGGER SiSoToiDa ON HOCSINH
FOR INSERT, UPDATE
AS
declare @A int = (select malop from inserted)

declare @SS int = (select x.SSTOIDA  from KHOILOP x, LOP y where  y.MAKHOI=x.MAKHOI AND y.MALOP=@A )

IF (SELECT COUNT(a.MAHS) FROM HOCSINH a WHERE a.MALOP=@A) > @SS
BEGIN
	print 'lop full'
	RollBack Tran
END
GO

--
ALTER TABLE SUCKHOE 
ADD CONSTRAINT fk_sk__constraint
 FOREIGN KEY (MAHS) 
 REFERENCES HOCSINH (MAHS)
 ON DELETE CASCADE;
 GO



 -- 3 khối lớp mầm chồi lá
INSERT INTO KHOILOP VALUES (N'Mầm',20)
INSERT INTO KHOILOP VALUES (N'Chồi',25)
INSERT INTO KHOILOP VALUES (N'Lá',30)

GO

INSERT INTO NGUOIDUNG (TAIKHOAN,MATKHAU,QUYEN) VALUES ('admin','33354741122871651676713774147412831195','Admin') -- admin

	

	
	

